"""Email Notification Service.

Sends email notifications for pipeline events:
- Success: Video published with title, video ID, and link
- Failure: Error details with log excerpt
- Optimization: Daily summary of analytics insights

Supports Gmail SMTP (free) or SendGrid (if configured).
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from typing import Optional, Dict, Any

from ..config import settings

logger = logging.getLogger(__name__)


class EmailNotificationService:
    """Send email notifications for pipeline events."""
    
    def __init__(self):
        """Initialize email service with config from settings."""
        self.smtp_host = getattr(settings, 'smtp_host', 'smtp.gmail.com')
        self.smtp_port = getattr(settings, 'smtp_port', 587)
        self.smtp_user = getattr(settings, 'smtp_user', '')
        self.smtp_password = getattr(settings, 'smtp_password', '')
        self.from_email = getattr(settings, 'notification_from_email', self.smtp_user)
        self.to_email = getattr(settings, 'notification_to_email', '')
        
        self._enabled = bool(self.smtp_user and self.smtp_password and self.to_email)
        
        if self._enabled:
            logger.info("Email notification service initialized")
        else:
            logger.warning("Email notifications disabled - missing SMTP configuration")
    
    @property
    def is_enabled(self) -> bool:
        """Check if email notifications are enabled."""
        return self._enabled and settings.features.email_notifications
    
    def send_success_notification(
        self,
        lesson_title: str,
        video_id: Optional[str] = None,
        thumbnail_generated: bool = False,
        duration_seconds: Optional[float] = None,
    ) -> bool:
        """Send notification for successful pipeline run.
        
        Args:
            lesson_title: Title of the generated lesson
            video_id: YouTube video ID if uploaded
            thumbnail_generated: Whether thumbnail was created
            duration_seconds: How long the pipeline took
            
        Returns:
            True if email sent successfully
        """
        if not self.is_enabled:
            return False
        
        subject = f"✅ AI Education: Published - {lesson_title}"
        
        video_url = f"https://youtube.com/watch?v={video_id}" if video_id else "Not uploaded"
        duration_str = f"{duration_seconds / 60:.1f} minutes" if duration_seconds else "Unknown"
        
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #4CAF50;">✅ Video Published Successfully!</h2>
            
            <table style="border-collapse: collapse; width: 100%; max-width: 500px;">
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Lesson:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{lesson_title}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Video ID:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{video_id or 'N/A'}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>YouTube:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                        <a href="{video_url}">{video_url}</a>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Thumbnail:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                        {'✅ Generated' if thumbnail_generated else '❌ Not generated'}
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px;"><strong>Duration:</strong></td>
                    <td style="padding: 10px;">{duration_str}</td>
                </tr>
            </table>
            
            <p style="margin-top: 20px; color: #666;">
                Generated by <strong>Self-Improving AI Education Engine</strong><br>
                {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </p>
        </body>
        </html>
        """
        
        return self._send_email(subject, html_content)
    
    def send_failure_notification(
        self,
        error: str,
        stage: str = "unknown",
        log_excerpt: Optional[str] = None,
    ) -> bool:
        """Send notification for failed pipeline run.
        
        Args:
            error: Error message
            stage: Stage where failure occurred
            log_excerpt: Last few lines of log
            
        Returns:
            True if email sent successfully
        """
        if not self.is_enabled:
            return False
        
        subject = f"❌ AI Education: Pipeline Failed at {stage}"
        
        log_html = f"<pre style='background: #f5f5f5; padding: 10px; overflow-x: auto;'>{log_excerpt}</pre>" if log_excerpt else ""
        
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #f44336;">❌ Pipeline Failed</h2>
            
            <table style="border-collapse: collapse; width: 100%; max-width: 500px;">
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Stage:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{stage}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Error:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd; color: #f44336;">{error}</td>
                </tr>
                <tr>
                    <td style="padding: 10px;"><strong>Time:</strong></td>
                    <td style="padding: 10px;">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</td>
                </tr>
            </table>
            
            {f"<h3>Log Excerpt:</h3>{log_html}" if log_excerpt else ""}
            
            <p style="margin-top: 20px; color: #666;">
                Check logs: <code>logs/pipeline_{datetime.now().strftime('%Y-%m-%d')}.log</code>
            </p>
        </body>
        </html>
        """
        
        return self._send_email(subject, html_content)
    
    def send_optimization_summary(
        self,
        videos_analyzed: int,
        avg_views: float,
        avg_engagement: float,
        recommendations: list,
    ) -> bool:
        """Send daily optimization summary.
        
        Args:
            videos_analyzed: Number of videos analyzed
            avg_views: Average view count
            avg_engagement: Average engagement rate
            recommendations: List of recommendations
            
        Returns:
            True if email sent successfully
        """
        if not self.is_enabled:
            return False
        
        subject = f"📊 AI Education: Daily Optimization Summary"
        
        recs_html = "".join([f"<li>{r}</li>" for r in recommendations[:5]])
        
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #2196F3;">📊 Daily Optimization Summary</h2>
            
            <table style="border-collapse: collapse; width: 100%; max-width: 500px;">
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Videos Analyzed:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{videos_analyzed}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Avg Views:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{avg_views:.0f}</td>
                </tr>
                <tr>
                    <td style="padding: 10px;"><strong>Avg Engagement:</strong></td>
                    <td style="padding: 10px;">{avg_engagement:.2%}</td>
                </tr>
            </table>
            
            <h3>Top Recommendations:</h3>
            <ul>
                {recs_html or "<li>No recommendations today</li>"}
            </ul>
            
            <p style="margin-top: 20px; color: #666;">
                {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </p>
        </body>
        </html>
        """
        
        return self._send_email(subject, html_content)
    
    def _send_email(self, subject: str, html_content: str) -> bool:
        """Send email via SMTP.
        
        Args:
            subject: Email subject
            html_content: HTML body content
            
        Returns:
            True if sent successfully
        """
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.from_email
            msg['To'] = self.to_email
            
            # Create plain text version
            plain_text = html_content.replace('<br>', '\n').replace('</p>', '\n')
            # Simple HTML tag removal for plain text
            import re
            plain_text = re.sub('<[^<]+?>', '', plain_text)
            
            msg.attach(MIMEText(plain_text, 'plain'))
            msg.attach(MIMEText(html_content, 'html'))
            
            logger.info(f"Sending email: {subject}")
            
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            
            logger.info(f"Email sent successfully to {self.to_email}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False


# Global instance
_notification_service: Optional[EmailNotificationService] = None


def get_notification_service() -> EmailNotificationService:
    """Get or create the notification service singleton."""
    global _notification_service
    if _notification_service is None:
        _notification_service = EmailNotificationService()
    return _notification_service
